config/routes.rb
BallinOcto::Application.routes.draw do
  devise_for :users

  resources :properties
  resources :users
  resources :friendships
  

  root :to => 'properties#index'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :friend_id, :user_id
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :owner, :class_name => "User", :foreign_key => "user_id"
  attr_accessible :approx_sqft, :bathrooms, :bedrooms, :city, :geo_lat, :geo_lon, :list_price, :street_name, :street_number, :street_suffix, :unit_number, :year_built, :zip_code
	validates :city, :street_name, :street_number, :owner, :presence => true
	
	geocoded_by :full_address, :latitude  => :geo_lat, :longitude => :geo_lon # ActiveRecord
	
	before_save :geocode

	def full_address
		[:unit_number, :street_number, :street_name, :street_suffix, :city, :zip_code].map{|m| self.send m }.join(" ")
		# self.zip_code + " " + self.city + " " + self.street_name + " " + self.street_suffix + " " + self.street_number + " " + self.unit_number
	end

	def owned_by?(user)
		owner == user
	end

	def belongs_to_friend?(user)
		user.friends.include?(owner)
	end

	def can_manage_property?(user)
		 owned_by?(user) || user.role == 'ADMIN'
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :properties
  validates :email, :presence => true, :uniqueness => true

  has_many :friendships
  has_many :friends, :through => :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :subscribers, :through => :inverse_friendships, :source => :user

  def login
		email[0...email.index('@')]
  end

  def has_friend?(user)
  	friends.include?(user)
  end

  def can_add_friend?(user)
  	!has_friend?(user)
  end

  def mutual_friendships
  	#friendships & inverse_friendships
  	friendships.joins('INNER JOIN friendships ff ON friendships.user_id = ff.friend_id and ff.user_id = friendships.friend_id').where(:user_id => id)
  end

  def notmutual_friendships
  	friendships - mutual_friendships
  end

  def my_subscribers
  	subscribers - friends 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :authenticate_user!
  protect_from_forgery
end

app/controllers/crud_controller.rb
class CrudController < ApplicationController
  def index
  	@properties = Property.all
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController


	def create

		#logger.debug 'returnpath:'
		#logger.debug session[:return_to]
		#logger.debug session.inspect

		friend = User.find params[:friend_id]
		unless current_user.can_add_friend?(friend)
	    flash[:notice] = "Unable to add friend."
	    redirect_to request.referer #session[:return_to]
	    return
		end
		@friendship = current_user.friendships.build(:friend_id => friend.id)
    flash[:notice] = @friendship.save ? "Added friend." : "Unable to add friend."
    redirect_to request.referer #session[:return_to]
	end

	def destroy
		@friendship = current_user.friendships.find(params[:id])
	  @friendship.destroy
	  flash[:notice] = "Removed friendship."
	  redirect_to current_user
	end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

	def show
		@property = Property.find params[:id]
	end

  def index
  	@properties = Property.all 
  	respond_to do |format|
			format.html # index.html.haml
			format.json { render :json => @properties }
		end 	 
  end

  def new
  	@property = Property.new
  end

  def create 
  	@property = current_user.properties.new(params[:property])
		respond_to do |format|
			if @property.save
				format.html { redirect_to(root_path, :notice => 'Property was successfully created.') }
				format.json { head :no_content }
			else
				format.html { render :action => "new" }
				format.json { render :json => @property.errors, :status => :unprocessable_entity }
			end
		end
  end	

  def destroy
		@property = Property.find(params[:id])
		if !@property.can_manage_property?(current_user) 
			respond_to do |format|
				format.html { render :nothing => true, :status => :forbidden }
				format.json  { render :nothing => true, :status => :forbidden }
			end
		else
			@property.destroy
			respond_to do |format|
				format.html { redirect_to(root_path, :notice => 'Property was successfully deleted.') }
				format.json { head :no_content }
			end
		end
  end

  def edit  	
		@property = Property.find(params[:id])
		if !@property.can_manage_property?(current_user) 
			respond_to do |format|
				format.html { render :nothing => true, :status => :forbidden }
				format.json  { render :nothing => true, :status => :forbidden }
			end
		end
  end

	def update
		@property = Property.find(params[:id])
		if @property.can_manage_property?(current_user)  
			respond_to do |format|
				if @property.update_attributes(params[:property])
					format.html { redirect_to(root_path, :notice => 'Property was successfully updated.') }
					format.json { head :no_content }
				else
					format.html { render :action => "edit" }
					format.json { render :json => @property.errors, :status => :unprocessable_entity }
				end
			end			
		else
			respond_to do |format|
				format.html { render :nothing => true, :status => :forbidden }
				format.json  { render :nothing => true, :status => :forbidden }
			end
		end
	end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find params[:id]
	end

  def index	
  	@users = User.all 
  	respond_to do |format|
			format.html # index.html.haml
			format.json { render :json => @users }
		end 	 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/crud/index.html.haml
%h1 Listing properties
%table
  %tr
    %th ZIP Code
    %th City
    %th Street Name
    %th Street Suffix
    %th Street Number
    %th Unit Number
    %th Latitude
    %th Longitude
    %th Year Built
    %th Approx sqft
    %th Bathrooms
    %th Bedrooms
    %th Price

  - @properties.each do |property|
    %tr
      %td= property.zip_code
      %td= property.city
      %td= property.street_name
      %td= property.street_suffix
      %td= property.street_number
      %td= property.unit_number
      %td= property.geo_lat
      %td= property.geo_lon
      %td= property.year_built
      %td= property.approx_sqft
      %td= property.bathrooms
      %td= property.bedrooms
      %td= property.list_price

 
%br
 

%p Find me in app/views/crud/index.html.haml

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BallinOcto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.5/leaflet.css" />
  <%= javascript_include_tag "application" %>
  <script src="http://cdn.leafletjs.com/leaflet-0.5/leaflet.js"></script>
  <%= yield :javascript %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body class="<%= controller.controller_name %>">
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Ballin-Octo</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Properties", properties_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Contact Us" %></li>
						<form class="navbar-search pull-left">
							<input type="text" class="search-query" placeholder="Search">
						</form>
          </ul>
          <ul class="nav pull-right">  
            <% if user_signed_in? %>
                <li><%= link_to current_user.login, user_path(current_user)%></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete%></li>
            <% else %>
                <li><%= link_to 'Register', new_user_registration_path %></il>
                <li><%= link_to 'Sign in', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
	<div class="container">
		<div class="row">
			<div class="span12">
        <% if notice %>
          <p class="notice"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert"><%= alert %></p>
        <% end %>
        <%= yield %>
			</div>
		</div>
	</div>


</body>
</html>

app/views/properties/_form.html.haml
= simple_form_for @property, :html => { :class => 'form-horizontal' } do |f|
  = f.input :zip_code
  = f.input :city
  = f.input :street_name
  = f.input :street_suffix
  = f.input :street_number
  = f.input :unit_number
  = f.input :geo_lon
  = f.input :geo_lat
  = f.input :year_built
  = f.input :bedrooms
  = f.input :bathrooms
  = f.input :approx_sqft
  = f.input :list_price
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), properties_path, :class => 'btn'

app/views/properties/edit.html.haml
- model_class = Property
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/properties/index.html.haml
- model_class = Property
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= "Full Address"
      %th= model_class.human_attribute_name(:year_built)
      %th= model_class.human_attribute_name(:bedrooms)
      %th= model_class.human_attribute_name(:bathrooms)
      %th= model_class.human_attribute_name(:approx_sqft)
      %th= model_class.human_attribute_name(:list_price)
      %th= model_class.human_attribute_name(:owner)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @properties.each do |property|      
      - scheme = property.owned_by?(current_user) ? 'my_property' : (property.belongs_to_friend?(current_user) ? 'friends_property' : '')
      %tr{ :class => scheme }
        %td= link_to property.full_address , property_path(property)
        %td= property.year_built
        %td= property.bedrooms
        %td= property.bathrooms
        %td= property.approx_sqft
        %td= property.list_price
        %td= link_to property.owner.login, user_path(property.owner) 
        %td{ :class => 'action_buttons' }
          - if property.can_manage_property?(current_user) 
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_property_path(property), :class => 'btn btn-mini'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), property_path(property), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'


= link_to t('.new', :default => t("helpers.links.new")), new_property_path, :class => 'btn btn-primary'

app/views/properties/new.html.haml
- model_class = Property
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/properties/show.html.haml
- model_class = Property
.page-header
  %h1=t '.title', :default => @property.full_address
%div
  #prop
    %p
      %strong= model_class.human_attribute_name(:zip_code) + ':'
      %br
      = @property.zip_code
    %p
      %strong= model_class.human_attribute_name(:city) + ':'
      %br
      = @property.city
    %p
      %strong= model_class.human_attribute_name(:street_name) + ':'
      %br
      = @property.street_name
    %p
      %strong= model_class.human_attribute_name(:street_suffix) + ':'
      %br
      = @property.street_suffix
    %p
      %strong= model_class.human_attribute_name(:street_number) + ':'
      %br
      = @property.street_number
    %p
      %strong= model_class.human_attribute_name(:unit_number) + ':'
      %br
      = @property.unit_number
    %p
      %strong= model_class.human_attribute_name(:geo_lon) + ':'
      %br
      = @property.geo_lon
    %p
      %strong= model_class.human_attribute_name(:geo_lat) + ':'
      %br
      = @property.geo_lat
    %p
      %strong= model_class.human_attribute_name(:year_built) + ':'
      %br
      = @property.year_built
    %p
      %strong= model_class.human_attribute_name(:bedrooms) + ':'
      %br
      = @property.bedrooms
    %p
      %strong= model_class.human_attribute_name(:bathrooms) + ':'
      %br
      = @property.bathrooms
    %p
      %strong= model_class.human_attribute_name(:approx_sqft) + ':'
      %br
      = @property.approx_sqft
    %p
      %strong= model_class.human_attribute_name(:list_price) + ':'
      %br
      = @property.list_price
    %p
      %strong= model_class.human_attribute_name(:owner) + ':'
      %br
      = link_to @property.owner.email, user_path(@property.owner)

  #map
  %script showmap_run()
  = content_for :javascript do 
    %script{ :type => 'text/javascript' }
      function showmap_run() {
      var map = L.map('map').setView([
      = @property.geo_lat
      , 
      = @property.geo_lon
      ], 16);
      L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18 }).addTo(map);

      L.marker([
      = @property.geo_lat
      ,
      = @property.geo_lon
      ]).addTo(map)
      }

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), properties_path, :class => 'btn'
  - if @property.can_manage_property?(current_user) 
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_property_path(@property), :class => 'btn'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), property_path(@property), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/property/index.html.haml
%h1 Listing properties
%table
  %tr
    %th ZIP Code
    %th City
    %th Street Name
    %th Street Suffix
    %th Street Number
    %th Unit Number
    %th Latitude
    %th Longitude
    %th Year Built
    %th Approx sqft
    %th Bathrooms
    %th Bedrooms
    %th Price

  - @properties.each do |property|
    %tr
      %td= property.zip_code
      %td= property.city
      %td= property.street_name
      %td= property.street_suffix
      %td= property.street_number
      %td= property.unit_number
      %td= property.geo_lat
      %td= property.geo_lon
      %td= property.year_built
      %td= property.approx_sqft
      %td= property.bathrooms
      %td= property.bedrooms
      %td= property.list_price

 
%br
 

%p Find me in app/views/property/index.html.haml

app/views/users/index.html.haml
- model_class = User
/- session[:return_to] = request.referer
/- logger.debug 'request.referer:'
/- logger.debug request.referer

.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= "User"
      %th      
  %tbody
    - @users.each do |user|
      %tr
        - if user!=current_user
          %td= link_to user.login , user_path(user)
          - if current_user.can_add_friend?(user)
            %td= link_to "Add Friend" , friendships_path(:friend_id => user), :method => :post
          - else
            %td

       

app/views/users/show.html.haml
- model_class = User
/- session[:return_to] = request.referer
/- logger.debug 'request.referer:'
/- logger.debug request.referer
/- logger.debug session.inspect

.page-header
  %h1=t '.title', :default => @user.login

%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email

%p
  %strong= model_class.human_attribute_name(:last_sign_in_at) + ':'
  %br
  = @user.last_sign_in_at

%p
  %strong= model_class.human_attribute_name(:current_sign_in_ip) + ':'
  %br
  = @user.current_sign_in_ip

%p
  %strong= model_class.human_attribute_name(:properties) + ':'
  %ul
    - @user.properties.each do |property|
      %li= link_to property.full_address, property_path(property)

%div{ :class => 'mutual_friends'}
  %strong= 'Mutual Friends:'
  %ul
    - @user.mutual_friendships.each do |friendship|      
      %li= (friendship.friend.login + '(' +  link_to("remove", friendship, :method => :delete) +')').html_safe

%div{ :class => 'notmutual_friends'}
  %strong= 'My Friends:'
  %ul
    - @user.notmutual_friendships.each do |friendship|      
      %li= (friendship.friend.login + '(' +  link_to("remove", friendship, :method => :delete) +')').html_safe

%div{ :class => 'my_subscribers'}
  %strong= 'My Subscribers:'
  %ul
    - @user.my_subscribers.each do |subscriber|
      %li= (subscriber.login + (@user.can_add_friend?(subscriber) ? '(' +  link_to("Add Friend", friendships_path(:friend_id => subscriber), :method => :post) +')' : '')).html_safe          


.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'  
  = link_to 'TODO Change Password', edit_user_password_path(current_user), :class => 'btn'  